title: test
description: test description

# theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme

copyright:
  revision: true

edit: true
addons_branch: true

addons:
  - github
  - i18n
  - analytics

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  
  # Specific to this theme
site_author: Bbscncom
repo_url: 'https://github.com/bbscncom/mcmoddevShare'
edit_on_github: true
github_docs_folder: true
logo: ''
site_favicon: ''
sticky_navigation: true
prev_next_buttons_location: None
prev_next_buttons_location: top
prev_next_buttons_location: bottom
prev_next_buttons_location: both
search_enabled: true
google_analytics: UA-XXXXX-Y
google_analytics_anonymize_ip: true
# The highlight.js library provides 79 different colours for their syntax highlighting. The default is github-gist.
hljs_style: github-gist
