title: mcmod入门分享
description: 版本1.12 
#remote_theme: carlosperate/jekyll-theme-rtd
remote_theme: just-the-docs/just-the-docs

just_the_docs:
  children: auto

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/ 
  - startserver.bat
sass:
  style: compressed
  
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag