title: test
description: test description

# theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme

copyright:
  revision: true

edit: true
addons_branch: true

addons:
  - github
  - i18n
  - analytics

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock

