source "https://rubygems.org"
gem "github-pages", "~> 230", group: :jekyll_plugins
gem "webrick"
#gem "jekyll", "~> 4.4.1"
#gem "just-the-docs"
#gem "jekyll-feed"
#gem "jekyll-sitemap"
#gem "jekyll-seo-tag"